D:\Python_Programs\VideoConference4k\videoconference4k\__init__.py: true
D:\Python_Programs\VideoConference4k\videoconference4k\capture\__init__.py: true
D:\Python_Programs\VideoConference4k\videoconference4k\capture\audio.py: true
D:\Python_Programs\VideoConference4k\videoconference4k\capture\video.py: true
D:\Python_Programs\VideoConference4k\videoconference4k\conference\__init__.py: true
D:\Python_Programs\VideoConference4k\videoconference4k\conference\multipeer.py: true
D:\Python_Programs\VideoConference4k\videoconference4k\conference\peer.py: true
D:\Python_Programs\VideoConference4k\videoconference4k\net\__init__.py: true
D:\Python_Programs\VideoConference4k\videoconference4k\net\async_.py: true
D:\Python_Programs\VideoConference4k\videoconference4k\net\sync.py: true
D:\Python_Programs\VideoConference4k\videoconference4k\remove_whitespaces.py: true
D:\Python_Programs\VideoConference4k\videoconference4k\rtc\__init__.py: true
D:\Python_Programs\VideoConference4k\videoconference4k\rtc\connection.py: true
D:\Python_Programs\VideoConference4k\videoconference4k\rtc\tracks.py: true
D:\Python_Programs\VideoConference4k\videoconference4k\stream\__init__.py: true
D:\Python_Programs\VideoConference4k\videoconference4k\stream\video.py: true
D:\Python_Programs\VideoConference4k\videoconference4k\utils\__init__.py: true
D:\Python_Programs\VideoConference4k\videoconference4k\utils\common.py: true
D:\Python_Programs\VideoConference4k\videoconference4k\utils\nvidia_codec.py: true
D:\Python_Programs\VideoConference4k\videoconference4k\version.py: true
_include_python: true
_include_typescript: false
_include_website: false
_scan_depth: 4
